In [2]:
import numpy as np

In [4]:
a=[1,2,3,4]
type(a)

list

In [23]:
b=np.array([1,2,3])
np.ndim(b)

1

In [24]:
c=np.array([1])
np.ndarray(c)

array([5.e-324])

In [32]:
e=np.array([[1,2,3],[2,3,4]])
np.ndim(e)

2

In [20]:
d[0][2]

np.int64(3)

In [27]:
d=np.array([[[1,2,3],[2,3,4],[2,4,5],[2,6,7]]])
np.ndim(d)

3

In [48]:
d[0][1][1]

np.int64(3)

In [33]:
d.shape

(1, 4, 3)

In [34]:
d.size

12

In [37]:
d[0][1]

array([2, 3, 4])

In [39]:
d[0][2]

array([2, 3, 4])

In [43]:
v=np.arange(1,100,2)
v

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [41]:
f=np.arange(1,10)
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
#create evenly spaced values
r=np.linspace(1,5,20)
r

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [49]:
#mathematical function
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [50]:
print(np.sum(a))

15


In [51]:
a.sum()

np.int64(15)

In [52]:
np.sum(a)

np.int64(15)

In [53]:
np.mean(a)

np.float64(3.0)

In [54]:
np.median(a)

np.float64(3.0)

In [55]:
np.std(a)

np.float64(1.4142135623730951)

In [56]:
np.max(a)

np.int64(5)

In [57]:
np.min(a)

np.int64(1)

In [58]:
np.var(a)

np.float64(2.0)

In [67]:
#rand fun generates random decimal numbers
np.random.seed(1) #same random output every time
np.random.rand(10)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [63]:
np.random.randint(1,100,5)

array([76,  6, 80, 65, 17], dtype=int32)

In [69]:
#slicing
a=np.array([10,20,30,40,50])
a[2]

np.int64(30)

In [70]:
a[0:4]

array([10, 20, 30, 40])

In [72]:
b=np.arange(1,50)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
b[21:25]

array([22, 23, 24, 25])

In [76]:
p=np.array([1,2,3,4,5,6])
p[1:4]

array([2, 3, 4])

In [78]:
p[:-1]

array([1, 2, 3, 4, 5])

In [82]:
u=np.array([6,3,9,1,2])
u

array([6, 3, 9, 1, 2])

In [84]:
u[:-3]

array([6, 3])

In [101]:
#filtering
u[u>2]
#boolean filtering
u>2

array([ True,  True,  True, False, False])

In [89]:
a1=np.arange(1,11)
a2=np.arange(15,25)

In [90]:
print(a1)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]
[15 16 17 18 19 20 21 22 23 24]


In [92]:
np.concatenate((a1,a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [93]:
np.split(a1,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [94]:
np.sort(a1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
print(a1+a2)

[16 18 20 22 24 26 28 30 32 34]


In [97]:
np.dot(a1,a2)#multiply

np.int64(1155)

In [99]:
a=np.array([[1,2],[3,4]])
b=np.array([[2],[4]])
np.dot(a,b)

array([[10],
       [22]])

In [100]:
print(a*b)

[[ 2  4]
 [12 16]]


In [4]:
#reshaping transform
import numpy as np
a=np.array([[5,6,7],[6,7,8],[7,8,9]])
print(a.reshape(1,-1))
print(a.reshape(-1,1))


[[5 6 7 6 7 8 7 8 9]]
[[5]
 [6]
 [7]
 [6]
 [7]
 [8]
 [7]
 [8]
 [9]]


In [5]:
a.flatten()
a

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [111]:
a.ravel()

array([1, 2, 3, 4])

In [6]:
np.vstack(a)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [7]:
np.hstack(a)

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [8]:
np.vsplit(a, 3)

[array([[5, 6, 7]]), array([[6, 7, 8]]), array([[7, 8, 9]])]


In [105]:
#odd
a3=np.arange(21,72,2)
print(a3.dtype)
a3=a3.astype("str")
a3

int64


array(['21', '23', '25', '27', '29', '31', '33', '35', '37', '39', '41',
       '43', '45', '47', '49', '51', '53', '55', '57', '59', '61', '63',
       '65', '67', '69', '71'], dtype='<U21')

In [106]:
a3=a3.astype("float")
a3

array([21., 23., 25., 27., 29., 31., 33., 35., 37., 39., 41., 43., 45.,
       47., 49., 51., 53., 55., 57., 59., 61., 63., 65., 67., 69., 71.])