In [2]:
import numpy as np

In [10]:
#Numpy array with values 1 to 20
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
#5x5 matrix with zeros
b=np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
#4x4 identity matrix
c=np.identity(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
#15 random integers
d=np.arange(15,30)
print(d.dtype)
d

int64


array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
d.size

15

In [39]:
d.shape

(15,)

In [43]:
#reshape (4,6) matrix
e=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
e.ndim
print(e.reshape(4,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [44]:
#2D
f=np.array([[2,3,4],[4,5,6]])
np.ndim(f)

2

In [45]:
#2D to 1D
f.ravel()

array([2, 3, 4, 4, 5, 6])

In [2]:
#even numbers from 1 to 50
g=np.arange(1,50,2)
g

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [58]:
#multiple of 5
h=np.arange(0,100,5)
print(h)
#maximum and minimum of array
print(max(h))
print(min(h))

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
95
0


In [59]:
#largest element of index position
i=np.array([20,56,78,43,22])
np.argmax(i)

np.int64(2)

In [61]:
#ascending order
j=np.array([20,56,78,43,22])
np.sort(j)

array([20, 22, 43, 56, 78])

In [67]:
#reverse without loops
k=np.array([2,5,6,7,8])
k[::-1]

array([8, 7, 6, 5, 2])

In [69]:
#element wise addition of two arrays
l=np.array([35,67,89,45])
m=np.array([43,56,7,8])
np.dot(l,m)

np.int64(6240)

In [78]:
#sub,mul,div on arrays
n=np.array([5,6,7,8])
o=np.array([2,3,3,4])
p1=n-o
p2=n*o
p3=n/o
print(p1,p2,p3)


[3 3 4 4] [10 18 21 32] [2.5        2.         2.33333333 2.        ]


In [79]:
#mean,median,SD
p=np.array([5,6,7,8])
print(np.mean(p))
print(np.median(p))
print(np.std(p))

6.5
6.5
1.118033988749895


In [4]:
#sum of rows and columns
q=np.array([[3,4,5],[6,7,8],[9,3,5]])
print(np.sum(q,axis=0)) #column
print(np.sum(q,axis=1))#row

[18 14 18]
[12 21 17]


In [11]:
#mul of two matrices
r=np.array([[3,4],[1,2]])
s=np.array([[2,1],[3,2]])
print(np.dot(r,s))

[[18 11]
 [ 8  5]]


In [16]:
#transpose
x=np.array([[2,3],[4,5]])
x.T

array([[2, 4],
       [3, 5]])