In [3]:
a=int(input("Enter student marks:"))
if a>95 :
    print("Topper")
elif a>=70:
    print("Average performers")
elif a<45:
    print("failed students")
else:
    print("fail")
    

Enter student marks: 45


fail


In [31]:
#1st sum
import numpy as np
a=np.random.randint(1,100,500)
a1=a[a>90]
print("Toppers",a1)
b1=a[(a>45) & (a<60)]
print("Average performers",b1)
c1=a[a<45]
print("Failed students",c1)




Toppers [96 92 95 99 94 93 95 97 92 99 95 94 91 91 92 92 95 92 96 94 98 95 91 95
 94 93 93 95 93 96 97 98 93 92 99 97 97 99 93 99 96 96 93 95 96 94 99 98
 98 97]
Average performers [55 49 56 51 57 49 58 58 54 51 51 52 49 58 50 53 59 49 49 50 47 54 49 48
 46 46 48 57 56 51 58 55 54 55 52 53 51 52 56 56 53 55 47 58 56 50 58 47
 46 46 46 47 52 50 55 47 57 51 51 58 59 59 49 59 57 48 53 58 56 47 52 48
 57]
Failed students [ 4 33  6 25 26 21  4 29 21 37  7 15 25 15  7 21 36 38  2 39  1  3  4 41
 30 37 11 37 20 29 24 20 30 26 35 25 26 39  9  5  7 35  8 26 13 24 14 35
 19 19 35 42 36 22 33 34 41  9 11 19 29 27  1  6 40 38  4 36 43 14 39  8
  2  1 37 19 16 14 44 11 33 38 34 10 28 14  7 43 38 24 13 17 19  9 15  7
 16 26 38 25 10 33 27 44  7 10 33 13 20 25 36 42 15 38 36 38 12 20  5 43
 25 14  3  6  8 14  4  6  3  8  6 17 42  6 19  9  6  6 23 40 43 19 39 19
 17  6 34  7 35 36 38 13 19 33  6 35 44 40  9 13 10 20 23 11 12  4  2  4
  9 40 42 17 39 28 18 11 11  5  1 31 41 31 23 20 44 44 29 35 43 37 2

In [37]:
#2nd sum
b=np.random.randint(500,5000,(4,3))
print(b)
b1=np.sum(b)
print("Total sales:",b1)
b2=np.max(b)
print("Highest Selling product:",b2)
b3=np.sum(b,axis=1)
print("Daily revenue trends:",b3)

[[1689 4336 1082]
 [3679 2696 1217]
 [2483 1516 3951]
 [1597 1990  853]]
Total sales: 27089
Highest Selling product: 4336
Daily revenue trends: [7107 7592 7950 4440]
